---
- name: Desinstalar apache
  apt: 
    name: nginx
    state: absent

- name: Desinstalar nginx
  apt: 
    name: nginx
    state: absent

- name: Borrar contenido carpeta /var/www/html
  file:
    path: /var/www/html/index.html
    state: absent
...
